cc_library(
    name = "greeter",
    srcs = ["greeter.cpp"],
    hdrs = ["include/core/greeter.h"],
    includes = ["include"],
    deps = ["//lib/util:str_utils"],
    visibility = ["//visibility:public"],
)
